#!/bin/bash
# This is an autogenerated file by sync-to-s3.sh
# Generated date and time: Sun Mar  9 10:49:23 EDT 2025    41531763
aws cloudformation create-stack \
--capabilities CAPABILITY_NAMED_IAM \
--stack-name ASR-Member-1741531763 \
--description "(SO0111) AWS Security Hub Automated Response & Remediation MEMBER Stack, automated-security-response-on-aws v2.2.0.cnxc.9" \
--template-url "https://sharr-deploy-116981786788-reference.s3.amazonaws.com/automated-security-response-on-aws/v2.2.0.cnxc.9/aws-sharr-member.template" \
--parameters \
  ParameterKey=LoadSCMemberStack,ParameterValue=yes \
  ParameterKey=LoadAFSBPMemberStack,ParameterValue=no \
  ParameterKey=LoadCIS120MemberStack,ParameterValue=no \
  ParameterKey=LoadCIS140MemberStack,ParameterValue=no \
  ParameterKey=LoadNIST80053MemberStack,ParameterValue=no \
  ParameterKey=LoadPCI321MemberStack,ParameterValue=no \
  ParameterKey=CreateS3BucketForRedshiftAuditLogging,ParameterValue=no \
  ParameterKey=LogGroupName,ParameterValue=aws-controltower/CloudTrailLogs \
  ParameterKey=Namespace,ParameterValue=41531763 \
  ParameterKey=SecHubAdminAccount,ParameterValue=340752811256
