#!/bin/bash
# This is an autogenerated file by sync-to-s3.sh
# Generated date and time: Tue Mar  4 22:24:49 EST 2025
aws cloudformation update-stack-set \
--stack-set-name AWSControlTower-SHARR-MemberRoles \
--description "(SO0111) AWS Security Hub Automated Response & Remediation ROLES Stack, automated-security-response-on-aws v2.2.0.cnxc.7" \
--template-url "https://sharr-deploy-008012068868-reference.s3.amazonaws.com/automated-security-response-on-aws/v2.2.0.cnxc.7/aws-sharr-member-roles.template" \
--capabilities CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND \
--tags Key=Solution,Value=automated-security-response-on-aws Key=Version,Value=v2.2.0.cnxc.7 Key=App,Value=SHARR \
--operation-preferences FailureToleranceCount=49,MaxConcurrentCount=50,RegionConcurrencyType=PARALLEL \
--permission-model SERVICE_MANAGED \
--call-as SELF \
--parameters \
  ParameterKey=SecHubAdminAccount,ParameterValue=211125410042 \
  ParameterKey=Namespace,ParameterValue=41145089
