#!/bin/bash
# This is an autogenerated file by sync-to-s3.sh
# Generated date and time: Thu Mar  6 22:39:01 EST 2025    41318741
aws cloudformation create-stack \
--capabilities CAPABILITY_NAMED_IAM \
--stack-name ASR-Member-Roles-1741318741 \
--description "(SO0111) AWS Security Hub Automated Response & Remediation ROLES Stack, automated-security-response-on-aws v2.2.0.cnxc.9" \
--template-url "https://sharr-deploy-008012068868-reference.s3.amazonaws.com/automated-security-response-on-aws/v2.2.0.cnxc.9/aws-sharr-member-roles.template" \
--parameters \
  ParameterKey=Namespace,ParameterValue=41318741 \
  ParameterKey=SecHubAdminAccount,ParameterValue=211125410042
