#!/bin/bash
# This is an autogenerated file by sync-to-s3.sh
# Generated date and time: Sun Mar  9 10:49:23 EDT 2025
aws cloudformation update-stack-set \
--stack-set-name AWSControlTower-SHARR-MemberRoles \
--description "(SO0111) AWS Security Hub Automated Response & Remediation ROLES Stack, automated-security-response-on-aws v2.2.0.cnxc.9" \
--template-url "https://sharr-deploy-116981786788-reference.s3.amazonaws.com/automated-security-response-on-aws/v2.2.0.cnxc.9/aws-sharr-member-roles.template" \
--capabilities CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND \
--tags Key=Solution,Value=automated-security-response-on-aws Key=Version,Value=v2.2.0.cnxc.9 Key=App,Value=SHARR \
--operation-preferences FailureToleranceCount=49,MaxConcurrentCount=50,RegionConcurrencyType=PARALLEL \
--permission-model SERVICE_MANAGED \
--call-as SELF \
--parameters \
  ParameterKey=SecHubAdminAccount,ParameterValue=340752811256 \
  ParameterKey=Namespace,ParameterValue=41531763
