#!/bin/bash
# This is an autogenerated file by sync-to-s3.sh
# Generated date and time: Sun Mar  9 10:49:23 EDT 2025
aws cloudformation update-stack-set \
--stack-set-name AWSControlTower-SHARR-Admin \
--description "(SO0111) AWS Security Hub Automated Response & Remediation ADMINISTRATOR Stack, automated-security-response-on-aws v2.2.0.cnxc.9" \
--template-url "https://sharr-deploy-116981786788-reference.s3.amazonaws.com/automated-security-response-on-aws/v2.2.0.cnxc.9/aws-sharr-deploy.template" \
--capabilities CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND \
--tags Key=Solution,Value=automated-security-response-on-aws Key=Version,Value=v2.2.0.cnxc.9 Key=App,Value=SHARR \
--operation-preferences FailureToleranceCount=49,MaxConcurrentCount=50,RegionConcurrencyType=PARALLEL \
--administration-role-arn arn:aws:iam::116981786788:role/service-role/AWSControlTowerStackSetRole \
--execution-role-name AWSControlTowerExecution \
--permission-model SELF_MANAGED \
--call-as SELF \
--accounts 340752811256 \
--regions us-east-1 \
--parameters \
ParameterKey=LoadAFSBPAdminStack,ParameterValue=no \
ParameterKey=LoadCIS120AdminStack,ParameterValue=no \
ParameterKey=LoadCIS140AdminStack,ParameterValue=no \
ParameterKey=LoadNIST80053AdminStack,ParameterValue=no \
ParameterKey=LoadPCI321AdminStack,ParameterValue=no \
ParameterKey=LoadSCAdminStack,ParameterValue=yes \
ParameterKey=ReuseOrchestratorLogGroup,ParameterValue=yes \
ParameterKey=UseCloudWatchMetrics,ParameterValue=yes \
ParameterKey=UseCloudWatchMetricsAlarms,ParameterValue=yes \
ParameterKey=TicketGenFunctionName,ParameterValue=""
