#!/bin/bash
# This is an autogenerated file by sync-to-s3.sh
# Generated date and time: Mon Mar  3 19:59:08 EST 2025
export NAMESPACE=41049948
aws cloudformation update-stack-set \
--stack-set-name AWSControlTower-SHARR-Member \
--description "(SO0111) AWS Security Hub Automated Response & Remediation MEMBER Stack, automated-security-response-on-aws v2.2.0.cnxc.7" \
--template-url "https://sharr-deploy-008012068868-reference.s3.amazonaws.com/automated-security-response-on-aws/v2.2.0.cnxc.7/aws-sharr-member.template" \
--parameters ParameterKey=CreateS3BucketForRedshiftAuditLogging,UsePreviousValue=false,ParameterValue=no ParameterKey=LoadAFSBPMemberStack,UsePreviousValue=false,ParameterValue=no ParameterKey=LoadCIS120MemberStack,UsePreviousValue=false,ParameterValue=no ParameterKey=LoadCIS140MemberStack,UsePreviousValue=false,ParameterValue=no ParameterKey=LoadNIST80053MemberStack,UsePreviousValue=false,ParameterValue=no ParameterKey=LoadPCI321MemberStack,UsePreviousValue=false,ParameterValue=no ParameterKey=LoadSCMemberStack,UsePreviousValue=false,ParameterValue=yes ParameterKey=LogGroupName,UsePreviousValue=true ParameterKey=SecHubAdminAccount,UsePreviousValue=true ParameterKey=Namespace,UsePreviousValue=false,ParameterValue= \
--capabilities CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND \
--tags Key=Solution,Value=automated-security-response-on-aws Key=Version,Value=v2.2.0.cnxc.7 Key=App,Value=SHARR \
--operation-preferences FailureToleranceCount=49,MaxConcurrentCount=50,RegionConcurrencyType=PARALLEL \
--administration-role-arn arn:aws:iam::008012068868:role/service-role/AWSControlTowerStackSetRole \
--execution-role-name AWSControlTowerExecution \
--permission-model SELF_MANAGED \
--call-as SELF \
--accounts 211125410042 \
--regions us-east-1 us-west-2
