#!/bin/bash
# This is an autogenerated file by sync-to-s3.sh
# Generated date and time: Thu Mar  6 22:39:01 EST 2025    41318741
aws cloudformation update-stack-set \
--stack-set-name AWSControlTower-SHARR-Member \
--description "(SO0111) AWS Security Hub Automated Response & Remediation MEMBER Stack, automated-security-response-on-aws v2.2.0.cnxc.9" \
--template-url "https://sharr-deploy-008012068868-reference.s3.amazonaws.com/automated-security-response-on-aws/v2.2.0.cnxc.9/aws-sharr-member.template" \
--capabilities CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND \
--tags Key=Solution,Value=automated-security-response-on-aws Key=Version,Value=v2.2.0.cnxc.9 Key=App,Value=SHARR \
--operation-preferences FailureToleranceCount=49,MaxConcurrentCount=50,RegionConcurrencyType=PARALLEL \
--administration-role-arn arn:aws:iam::008012068868:role/service-role/AWSControlTowerStackSetRole \
--execution-role-name AWSControlTowerExecution \
--permission-model SELF_MANAGED \
--call-as SELF \
--parameters \
  ParameterKey=LoadSCMemberStack,ParameterValue=yes \
  ParameterKey=LoadAFSBPMemberStack,ParameterValue=no \
  ParameterKey=LoadCIS120MemberStack,ParameterValue=no \
  ParameterKey=LoadCIS140MemberStack,ParameterValue=no \
  ParameterKey=LoadNIST80053MemberStack,ParameterValue=no \
  ParameterKey=LoadPCI321MemberStack,ParameterValue=no \
  ParameterKey=CreateS3BucketForRedshiftAuditLogging,ParameterValue=no \
  ParameterKey=SecHubAdminAccount,ParameterValue=211125410042 \
  ParameterKey=LogGroupName,ParameterValue=aws-controltower/CloudTrailLogs \
  ParameterKey=Namespace,ParameterValue=41318741
